
podfile: tests/ios/Podfile

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3
      language: objective-c
    - os: osx
      osx_image: xcode7.2
      xcode_sdk: iphonesimulator9.2
      language: objective-c


before_install:
#  - git submodule update --init --recursive
#  - brew update || brew update
#  - brew outdated xctool || brew upgrade xctool
  - gem install xcpretty --no-rdoc --no-ri --no-document

script:
- open -b com.apple.iphonesimulator
- set -o pipefail && xcodebuild test -project tests/ios/LzmaSDK-ObjC.xcworkspace -scheme LzmaSDK-ObjCTests -destination 'platform=iOS Simulator,name=iPhone 4s,OS=8.4' | xcpretty -c
- set -o pipefail && xcodebuild test -project tests/ios/LzmaSDK-ObjC.xcworkspace -scheme LzmaSDK-ObjCTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' | xcpretty -c
- set -o pipefail && xcodebuild test -project tests/ios/LzmaSDK-ObjC.xcworkspace -scheme LzmaSDK-ObjCTests -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=9.3' | xcpretty -c
