#language: objective-c

xcode_workspace: tests/ios/LzmaSDK-ObjC.xcworkspace
xcode_scheme: LzmaSDK-ObjC

podfile: tests/ios/Podfile

# current
#osx_image: xcode7.2
#xcode_sdk: iphonesimulator9.2

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3
      language: objective-c
    - os: osx
      osx_image: xcode7.2
      xcode_sdk: iphonesimulator9.2
      language: objective-c


before_install:
#  - git submodule update --init --recursive
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool
